### ISSUE TITLE
KeyError: RIOT

### ISSUE THREAD

**Issue by GitHubEmploy** [steveman1123/stonkBot#3]
It says this as an error in the last 10 minutes when using paper trading.

**Comment by steveman1123** [comment]
I've not seen "key error: riot" before. If you've got the right keys in the apikeys.txt file, and moved the stockStuff folder out of the repo (as shown in the readme), then it may be something wrong on alpaca's end. Do you have the error code verbatim?

**Comment by GitHubEmploy** [comment]
No, I do not know what verbatim is, and the keys are correct because I can access my account status, and it only happens in the last 10 minutes when it tries too trade the stocks.

**Comment by steveman1123** [comment]
Verbatim means exactly as it was shown (in the terminal). Did you also make sure to set the isPaper variable in alpacafxns to 1?

**Comment by GitHubEmploy** [comment]
To both of your questions, the answer is yes.

**Comment by steveman1123** [comment]
Okay. I don't think I can help you more unless I see the exact error copied from the output.

**Comment by GitHubEmploy** [comment]
okay, I will run the code and show the output at 12:50

**Comment by GitHubEmploy** [comment]
Traceback (most recent call last):
  File "/Users/mohit/PycharmProjects/AutoStockTrader/stonkBot/stonkBot.py", line 22, in <module>
    main()
  File "/Users/mohit/PycharmProjects/AutoStockTrader/stonkBot/stonkBot.py", line 9, in main
    algos.mainAlgo() #used to easily switch between the different algos in the algo file
  File "/Users/mohit/PycharmProjects/AutoStockTrader/stonkBot/alpacaalgos.py", line 66, in mainAlgo
    check2buy(latestTrades, minBuyPow, buyPowMargin, minDolPerStock)
  File "/Users/mohit/PycharmProjects/AutoStockTrader/stonkBot/alpacaalgos.py", line 181, in check2buy
    latestTrades[symb][0] = str(a.o.dt.date.today())
KeyError: 'OPTT'

**Comment by GitHubEmploy** [comment]
I think that it has that error for some of the stocks, and that RIOT and OPTT are stocks that are not there

**Comment by steveman1123** [comment]
Are you up to date? I think I fixed that over the weekend. Try pulling the latest version

**Comment by GitHubEmploy** [comment]
oh, ok I think that I will update the source and see if it will work after that. I will close this problem now, and thank you for all your help.

**Comment by GitHubEmploy** [comment]
BY THE WAY, the way you fixed that problem is really smart
