### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GitHubEmploy** [steveman1123/stonkBot#5]
Hey, so this is really weird because it happened after a while, but it spat this out:Market is open
Portfolio val is $5000.96. Sell targets are 1.2 or 0.7
Updating stock list
Getting MarketWatch data...
page 1 of 3
Can withdrawl $1000 safely.
Done buying
Tradable Stocks:
page 2 of 3
page 3 of 3
Getting stocksunder1 data...
Removing Duplicates...
Done getting stock lists
Exception in thread listUpdate:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/momo/PycharmProjects/autostocktrader/AI/AutoStockTrader5.0/alpacaalgos.py", line 203, in updateStockList
    gainerDates = `a.o.getGainers(list(dict.fromkeys(a.o.getList()+[e['symbol']` for e in a.getPos()]))) #combine nasdaq list & my stocks & remove duplicates - order doesn't matter
  File "/home/momo/PycharmProjects/autostocktrader/AI/AutoStockTrader5.0/otherfxns.py", line 236, in getGainers
    b = goodBuy(e)
  File "/home/momo/PycharmProjects/autostocktrader/AI/AutoStockTrader5.0/otherfxns.py", line 194, in goodBuy
    while(float(dateData[startDate][1])/float(dateData[startDate+1][1])<firstJumpAmt and startDate<min(days2look,len(dateData)-2)):
IndexError: list index out of range

**Comment by GitHubEmploy** [comment]
Correct me if I'm wrong, but I believe you fixed this this new version, yes?

**Comment by steveman1123** [comment]
Sorry, I've been afk for the past few days. That's an interesting one, I'll look into it

**Comment by GitHubEmploy** [comment]
I have tried the new code, and it works perfectly, so I will close the issue now

**Comment by GitHubEmploy** [comment]
Accidentally Closed it 😁

**Comment by GitHubEmploy** [comment]
To get back to you on this, on the first day of running this, it does not have this error, but on the second, it does, and it can cause alot of problems. I feel like this is a major problem, because this does not allow functionality for more than a single day.

**Comment by steveman1123** [comment]
So my guess is that looking at the code:

   if(**startDate>=len(dateData)**): #if a stock returns nothing or very few data pts
      validBuy = "Few data points available"
    else:
      validBuy = "initial jump not found"
      while(float(dateData[startDate][1])/float(dateData[startDate+1][1])<firstJumpAmt and **startDate<min(days2look,len(dateData)-2)**):
        startDate += 1

The first conditional checks if there's enough data, but then the second one checks again on a smaller index, so I changed the first conditional to read

if(startDate>=len(dateData)-2)

I'd also suggest clearing any csv files that are already saved, it could be that one of them pulled bad data (that was an issue in the getHistory function, but should be resolved in the lastest version)

**Comment by GitHubEmploy** [comment]
Okay cool, I will try that when the stock market opens again tomorrow

**Comment by GitHubEmploy** [comment]
Also, I don't feel like this needs to be. anew issue, so I will list it here. 
Tradable Stocks:
symb	initial jump	predicted jump (+/- 3wks)	change from buy	change from close
----	------------	-------------------------	---------------	-----------------
SONN	2020-08-24	2020-09-28			1.0		1.0
DXLG	2020-08-27	2020-10-01			0.94		1.02

The symbols and initial jumps are off from the gollum's

**Comment by GitHubEmploy** [comment]
Ahhh, yes, that fixed the problem.
